//
//  CheckInAndOutDateStyleKit.swift
//  JetEx
//
//  Created by Cuong on 6/29/16.
//  Copyright (c) 2016 P5. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CheckInAndOutDateStyleKit : NSObject {

    //// Drawing Methods

    public class func drawCheckOutDate(frame: CGRect = CGRect(x: 31, y: 30, width: 200, height: 51)) {
        //// Color Declarations
        let color = UIColor(red: 0.404, green: 0.259, blue: 0.565, alpha: 0.200)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: frame.minX, y: frame.minY, width: floor((frame.width) * 0.50000 + 0.5), height: frame.height))
        color.setFill()
        rectanglePath.fill()
    }

    public class func drawCheckInDate(frame: CGRect = CGRect(x: 31, y: 31, width: 138, height: 51)) {
        //// Color Declarations
        let color = UIColor(red: 0.404, green: 0.259, blue: 0.565, alpha: 0.200)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: frame.minX + floor((frame.width) * 0.50000 + 0.5), y: frame.minY, width: frame.width - floor((frame.width) * 0.50000 + 0.5), height: frame.height))
        color.setFill()
        rectanglePath.fill()
    }

    public class func drawDateBetweenCheckInAndOutDate(frame: CGRect = CGRect(x: 31, y: 30, width: 172, height: 51)) {
        //// Color Declarations
        let color = UIColor(red: 0.404, green: 0.259, blue: 0.565, alpha: 0.200)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: frame.minX, y: frame.minY, width: frame.width, height: frame.height))
        color.setFill()
        rectanglePath.fill()
    }

}
