//
//  DateIndicatorStyleKit.swift
//  JetEx
//
//  Created by Cuong on 6/23/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class DateIndicatorStyleKit : NSObject {

    //// Drawing Methods

    public class func drawDateIndicator(xIndicator: CGFloat = 102, indFrame: CGRect = CGRect(x: 86, y: 28, width: 89, height: 42)) {
        //// Color Declarations
        let strokeColor = UIColor(red: 0.600, green: 0.600, blue: 0.600, alpha: 1.000)
        let fillColor = UIColor(hex: 0xF6F6F6)

        //// Variable Declarations
        let yIndicator: CGFloat = indFrame.origin.y

        //// Frames
        let arrowFrame = CGRect(x: xIndicator, y: yIndicator, width: 18, height: 9)
        let indicatorFrame = CGRect(x: indFrame.origin.x, y: indFrame.origin.y, width: indFrame.size.width, height: indFrame.size.height)


        //// Check Date Indicator Drawing
        let checkDateIndicatorPath = UIBezierPath()
        checkDateIndicatorPath.move(to: CGPoint(x: arrowFrame.minX + 9, y: arrowFrame.minY + 0.1))
        checkDateIndicatorPath.addCurve(to: CGPoint(x: arrowFrame.minX + 17.9, y: arrowFrame.minY + 9), controlPoint1: CGPoint(x: arrowFrame.minX + 9, y: arrowFrame.minY + 0.1), controlPoint2: CGPoint(x: arrowFrame.minX + 16.92, y: arrowFrame.minY + 8.01))
        checkDateIndicatorPath.addLine(to: CGPoint(x: indicatorFrame.maxX, y: indicatorFrame.minY + 9))
        checkDateIndicatorPath.addLine(to: CGPoint(x: indicatorFrame.maxX, y: indicatorFrame.maxY))
        checkDateIndicatorPath.addLine(to: CGPoint(x: indicatorFrame.minX, y: indicatorFrame.maxY))
        checkDateIndicatorPath.addLine(to: CGPoint(x: indicatorFrame.minX, y: indicatorFrame.minY + 9))
        checkDateIndicatorPath.addLine(to: CGPoint(x: arrowFrame.minX + 0.1, y: arrowFrame.minY + 9))
        checkDateIndicatorPath.addCurve(to: CGPoint(x: arrowFrame.minX + 9, y: arrowFrame.minY + 0.1), controlPoint1: CGPoint(x: arrowFrame.minX + 1.09, y: arrowFrame.minY + 8.01), controlPoint2: CGPoint(x: arrowFrame.minX + 9, y: arrowFrame.minY + 0.1))
        checkDateIndicatorPath.addLine(to: CGPoint(x: arrowFrame.minX + 9, y: arrowFrame.minY + 0.1))
        checkDateIndicatorPath.close()
        fillColor.setFill()
        checkDateIndicatorPath.fill()
        strokeColor.setStroke()
        checkDateIndicatorPath.lineWidth = 1
        checkDateIndicatorPath.stroke()
    }

}
